services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    container_name: qdrant_db

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama
    container_name: ollama_service
    restart: unless-stopped
    dns:
      - 8.8.8.8     # Google DNS
      - 1.1.1.1     # Cloudflare DNS


  postgres:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  fastapi_app:
    build: .
    container_name: fastapi_app
    working_dir: /app/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - qdrant
      - ollama
    env_file:
      - ./.env
    volumes:
      - .:/app
    restart: always

  streamlit:
    build: .
    container_name: streamlit
    working_dir: /app/frontend
    command: streamlit run streamlit.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - fastapi_app
    environment:
      - API_BASE=http://fastapi_app:8000
    restart: always

volumes:
  postgres_data:    
  qdrant_data: